USE adlister_db;

show tables;
CREATE TABLE IF NOT EXISTS users(
  id INT UNSIGNED AUTO_INCREMENT,
  username VARCHAR(40) NOT NULL ,
  email VARCHAR(45) NOT NULL ,
  password VARCHAR(45) NOT NULL ,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ads(
  id INT UNSIGNED AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL ,
  title VARCHAR(50) NOT NULL ,
  description TEXT NOT NULL ,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id)
);